# Generated by Django 3.0.6 on 2026-09-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_emergencyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyprofile',
            name='family_mobile_numbers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
